using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataMiningConsole
{
    /// <summary>
    /// The DataSourceOption enum provides options for data source when testing the algorithm in this project.
    /// </summary>
    public enum DataSourceOption
    {
        /// <summary>
        /// Test the algorithm using the default dataset.
        /// </summary>
        DefaultTestData,

        /// <summary>
        /// Test the algorithm using the dataset generated by the DataGenerator class.
        /// </summary>
        GenerateNewData
    }
}
